# Taps
tap "qmk/qmk"

# Brews
brew "composer"

brew "git"

brew "mysql"

brew "nvm"

brew "php"

brew "phpunit"

# brew "qmk/qmk/qmk"

brew "redis"

# Casks
cask "anki"

cask "audio-hijack"

cask "bitwarden"

cask "brave-browser"

cask "dbeaver-community"

cask "discord"

cask "docker"

cask "eloston-chromium"

cask "firefox"

cask "google-chrome"

# cask "insomnia"

cask "iterm2"

cask "keepassxc"

# cask "librewolf" --no-quarantine

cask "loopback"

cask "nordvpn"

cask "numi"

cask "obs"

cask "obsidian"

cask "phpstorm"

cask "postman"

cask "prusaslicer"

cask "rectangle"

cask "spotify"

cask "stats"

cask "steam"

cask "tableplus"

cask "via"

cask "visual-studio-code"