#!/bin/bash

ln -s $DOTFILES_CONFIG/alacritty $HOME/.config
ln -s $DOTFILES_CONFIG/karabiner $HOME/.config
ln -s $DOTFILES_CONFIG/newsboat $HOME/.config
ln -s $DOTFILES_CONFIG/nvim $HOME/.config
ln -s $DOTFILES_CONFIG/sketchybar $HOME/.config
ln -s $DOTFILES_CONFIG/tmux $HOME/.config
ln -s $DOTFILES_CONFIG/skhd $HOME/.config
ln -s $DOTFILES_CONFIG/yabai $HOME/.config
ln -s $DOTFILES_CONFIG/zsh/.zshrc $HOME/.config/zsh

